apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
  type: NodePort