apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mu-architecture-demo
  labels:
    name: mongo
    app: mongo
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017

  
