---
apiVersion: v1
kind: Service
metadata:
  name: trade-imdg-service
  labels:
    app: trade-imdg
spec:
  ports:
  - port: 1111
    name: trade-imdg-port
    targetPort: 1111
    protocol: TCP
  selector:
    app: trade-imdg
  type: LoadBalancer